# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc372cb70cb96929984bc744ca192567884e1bf71adc274a26986b19952dca73c5d634e4386e554096e294041628ef81afdc855b7ae705c74ae25a87f05e44ad

test:
  secret_key_base: 60e28ca0770a4f15bcee503e66e6423535a72e7927b477da1f25a540bb3c5bf6f2339d732bc82cd1684fdad9a04140a9c880820834164b31502229d1c51a5b48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
